# Generated by Django 3.0.2 on 2020-01-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('player_count', models.PositiveIntegerField()),
                ('current_player', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
