# Generated by Django 3.0.2 on 2020-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200107_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('player_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
